# Generated by Django 5.0.3 on 2024-03-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Themes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, unique=True, verbose_name='ThemeTitle')),
                ('description1', models.TextField(null=True, verbose_name='ThemeDescription1')),
            ],
            options={
                'verbose_name': 'Theme',
                'db_table': 'themes',
            },
        ),
    ]
