# Generated by Django 5.0.3 on 2024-03-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0003_alter_themes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themes',
            name='image',
            field=models.ImageField(default='themes/theme.jpg', upload_to='themes', verbose_name='ThemeImage'),
        ),
    ]
