# Generated by Django 5.0.3 on 2024-03-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, unique=True, verbose_name='Pupil name')),
                ('month_1', models.IntegerField(null=True, verbose_name='First month')),
                ('month_2', models.IntegerField(null=True, verbose_name='Second month')),
                ('month_3', models.IntegerField(null=True, verbose_name='Third month')),
                ('all_points', models.IntegerField(null=True, verbose_name='All points')),
            ],
            options={
                'verbose_name': 'Children_list',
                'db_table': 'children',
            },
        ),
    ]
