# Generated by Django 5.0.3 on 2024-03-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pupil',
            options={'ordering': ('id',), 'verbose_name': 'Children_list'},
        ),
        migrations.AddField(
            model_name='pupil',
            name='image',
            field=models.ImageField(default='pupil_logo.jpg', upload_to='logos', verbose_name='Pupil_image'),
        ),
    ]
