# Generated by Django 5.0.3 on 2024-03-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0002_alter_pupil_options_pupil_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='image',
            field=models.ImageField(default='logos/pupil_logo.jpg', upload_to='logos', verbose_name='Pupil_image'),
        ),
    ]
